Numpy array stores homogeneous type of data.

Numpy is a Python library -- used for working in arrays.

-- It also has functions forworking in domains of linear algebra and matrices.

-- Numpy was created in 2005 by Travis Oliphant

In [2]:
# backward and forward indexing is possible.
# slicing is possible.
# data manipulation is possible.

In [3]:
import numpy as np

In [4]:
lst = [1,3,6,7,89,43,52,5,6,4,56] 

In [5]:
arr1 = np.array(lst)
arr1

array([ 1,  3,  6,  7, 89, 43, 52,  5,  6,  4, 56])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
print(type(arr1))

<class 'numpy.ndarray'>


In [8]:
arr2 = np.array([34,79,91,32,21,18,39])
arr2

array([34, 79, 91, 32, 21, 18, 39])

In [9]:
type(arr2)

numpy.ndarray

In [10]:
print(type(arr2))

<class 'numpy.ndarray'>


In [11]:
arr3 = np.array([2,3,5,78.34,3.88,77.9,1.90], dtype = int) # here dtype is used to convert datatype of array elements.
arr3

array([ 2,  3,  5, 78,  3, 77,  1])

In [12]:
# 2D Array
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = np.int32)
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [13]:
arr4[0]

array([1, 2, 3], dtype=int32)

In [14]:
arr3[0] = 100  # replace 
arr3

array([100,   3,   5,  78,   3,  77,   1])

In [15]:
arr5 = arr3 + arr2
arr5

array([134,  82,  96, 110,  24,  95,  40])

### Zeros, Ones and Arange

In [16]:
# zeros, ones and arange

a = np.zeros(100)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
a1 = np.ones(10, dtype = int)
a1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
a2 = np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a3 = np.arange(10, dtype = float)
a3

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Reshape

In [20]:
# reshape : It needs proper quantity of elements to reshape it.
a3.reshape(5,2)

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [21]:
print(a3)
print(a3.reshape(5,2))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


### Attributes in Numpy

In [22]:
# attributes in numpy
# ndim : to check dimensions of array

arr4.ndim

2

In [23]:
#dtype
arr4.dtype

dtype('int32')

In [24]:
#shape
arr4.shape

(3, 3)

In [25]:
#itemsize
arr4.itemsize

4

In [26]:
#nbytes
arr4.nbytes

36

In [27]:
arr5 = np.array(['a','e','i','o','u'])
arr5

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [28]:
arr5.itemsize

4

In [29]:
arr5.nbytes

20

### Mathematical Operation

Mathematical operation only when length of arrays are same.

We can count the length of array through len().

In [30]:
distance = np.array([12,34,56,78])
time = np.array([1,2,3,4])

In [31]:
distance + time

array([13, 36, 59, 82])

In [32]:
distance -time

array([11, 32, 53, 74])

In [33]:
distance * time

array([ 12,  68, 168, 312])

In [34]:
distance / time

array([12.        , 17.        , 18.66666667, 19.5       ])

In [35]:
distance // time

array([12, 17, 18, 19])

In [36]:
distance % time

array([0, 0, 2, 2])

In [37]:
distance * 2

array([ 24,  68, 112, 156])

## Matrix

In [38]:
X = np.array([[2,4,6],[6,8,10],[3,6,9]])
X

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [ 3,  6,  9]])

In [39]:
# to fetch single element in matrix
X[1,1]

np.int64(8)

In [40]:
X[2,2] = 19
X

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [ 3,  6, 19]])

In [41]:
# to fetch a column of matrix.
X[:,1]

array([4, 8, 6])

In [42]:
# to fetch a row of matrix.
X[2]

array([ 3,  6, 19])

In [43]:
X[2, :]

array([ 3,  6, 19])

In [44]:
# np.bincount : it is first convert array into ascending order then count each element present in array and those values are not present in array of 
# ascending order that will be counted as 0.

X1 = np.array([2,3,4,5,5,6,7,0,0,1,1,2,3,5,2,1,1,10])
X1

array([ 2,  3,  4,  5,  5,  6,  7,  0,  0,  1,  1,  2,  3,  5,  2,  1,  1,
       10])

In [45]:
np.bincount(X1)

array([2, 4, 3, 2, 1, 3, 1, 1, 0, 0, 1])

In [46]:
arr1

array([ 1,  3,  6,  7, 89, 43, 52,  5,  6,  4, 56])

In [47]:
arr1[arr1>8]

array([89, 43, 52, 56])

In [48]:
# it apply operation on each value insdie array one by one.
arr1>8

array([False, False, False, False,  True,  True,  True, False, False,
       False,  True])

In [49]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [50]:
arr4[2]

array([7, 8, 9], dtype=int32)

In [51]:
arr4[2:3]

array([[7, 8, 9]], dtype=int32)

In [52]:
# Reversing a 3D array

arr_3D = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr_3D

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [53]:
np.flip(arr_3D)

array([[[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]])

In [54]:
np.flip(arr_3D, axis = 1)

array([[[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]]])

In [59]:
arr_4D = np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
arr_4D

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [60]:
np.flip(arr_4D)

array([[[[12, 11, 10],
         [ 9,  8,  7],
         [ 6,  5,  4],
         [ 3,  2,  1]]]])

In [61]:
np.flip(arr_4D, axis = 1)

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [62]:
np.flip(arr_4D, axis = 2)

array([[[[10, 11, 12],
         [ 7,  8,  9],
         [ 4,  5,  6],
         [ 1,  2,  3]]]])

In [64]:
np.flip(arr_4D, axis = 3)

array([[[[ 3,  2,  1],
         [ 6,  5,  4],
         [ 9,  8,  7],
         [12, 11, 10]]]])

In [66]:
# min, max, sum
print(arr_4D.min())
print(arr_4D.max())
print(arr_4D.sum())

1
12
78


In [68]:
# Random
# random.randint is used to create random numbers through numpy library.

x = np.random.randint(1,101,20)
x

array([68,  8, 82, 18, 29, 62, 38, 65, 55, 17, 50, 72, 25, 77, 80,  1,  8,
       29, 34, 20], dtype=int32)